### ISSUE TITLE
Investigate colony creation bundling

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#1058]
- Stage 1
        - Bundle 1:
            - Create Colony
            - Create Token
            - Assign Token
            - Mint Token
            - Claim Tokens
            - OneTxPayment Extension
            - Expenditures Extension
        - Bundle 2:
            - Create Colony
            - Assign Token
            - OneTxPayment Extension
            - Expenditures Extension
    - Stage 2
        - Bundle 3:
            - Multisig only
        - Bundle 4:
            - Governance only
        - Bundle 5:
            - Multisig + Governance
    - Stage 3
        - Bundle 6:
            - Airdropping tokens or just reputation

**Comment by arrenv** [comment]
@kronosapiens, I came across these as well, which may be more versatile options if feasible.

- [https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/Multicall.sol](https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/Multicall.sol)
- [https://github.com/safe-global/safe-contracts/blob/da66b45ec87d2fb6da7dfd837b29eacdb9a604c5/contracts/libraries/MultiSend.sol](https://github.com/safe-global/safe-contracts/blob/da66b45ec87d2fb6da7dfd837b29eacdb9a604c5/contracts/libraries/MultiSend.sol)

**Comment by area** [comment]
Assuming it works with Etherrouters (which I believe it should), a Multicall-esque implementation should be our preference here.

**Comment by area** [comment]
The `feat/multicall` branch now exists with the first tentative steps for this.
