### ISSUE TITLE
Create Simple Decisions extension

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#1068]
See spec here:

- https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=1018%3A54646
- https://www.notion.so/colony/Simple-Decisions-2d869923870640a5889f9f24b183c65b

**Comment by area** [comment]
After a call about this, to keep things as straightforward as possible for front-end, as well, we're going to try and keep it inside the existing motions extension with a 'special' action that indicates that it doesn't need to do anything/be finalized. The one wrinkle is that, as it's not finalizable, and it should go straight to closed. I think we deprecate the `finalized` boolean, and rework `getMotionState` to account for that, but there might be other things lurking that I haven't realised.
