### ISSUE TITLE
Emit event for the `makeArbitraryTransactions` function

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyNetwork#1103]
## Description

In order to be able to easily retrieve the transaction hash of an arbitrary transaction, which, is specifically being used by the Safe Control feature at the moment, we need to have an event emitted for the `makeArbitraryTransactions` function.

The main immediate use case for this emitted event is for the transaction hash to be used for the AMB monitor (https://alm-xdai.herokuapp.com/), required by the Safe Control feature to finalise the transaction on the destination chain.

**Comment by area** [comment]
Closed by #1104
