### ISSUE TITLE
Move to three point grading scale.

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#154]
As part of our feedback from Daniel Kronovet, he suggested migrating from a five-point grading scale to a three-point grading scale, denoting inadequate, adequate, and excellent. This is something we would like to implement.

Currently, a six-point scale is used (0-5, inclusive). The new scale should be 1-3 inclusive. For the worker, a '1' indicates a failure to complete the task, and should result in loss of reputation equal in magnitude to that they would have gained if they were rated a '2'. A '2' should be seen as the normal and expected rating for some work, and the worker gains reputation equal to the token payout received. A '3' indicates going above and beyond the call of duty, and should result in a reputation gain equal to 1.5 that which they would have gained if rated '2'.

Unlike the current implementation, these same factors should be used for the rating of the manager (-1, 1, 1.5).

This scale is now not linear, and so the half-point penalization for not committing or revealing the rating they were meant to submit should be removed, and replaced by a direct reputation penalty, equal to half the reputation they would have gained if they were rated a '1'.

**Optional:** The [whitepaper](https://circleci.com/gh/JoinColony/Colony-Whitepaper) will need to be amended to described this new implementation. This can be done by the same person who implements this on the contract-side, for bonus points, or not.

Have I missed anything, @elenadimitrova, or would you suggest any changes to the above? This is appropriate for 'good first issue' once we've agreed on the definition of the work.

**Comment by elenadimitrova** [comment]
Sounds good. Just to clarify the case of missing rating penalties:
- What do we assume the missing rating to be? In the current solution we assume 5 for both manager and worker. Here will it be a '3'?
- Clarifying the penalty amount from this:
>reputation penalty, equal to half the reputation they would have gained if they were rated a '1'
The reputation they gain if they were rated a '1' would be '-1' and the penalty therefore '-0.5'? That's the same as the current implementation right?

**Comment by area** [comment]
> What do we assume the missing rating to be? In the current solution we assume 5 for both manager and worker. Here will it be a '3'?

Yeah, I guess so. Benefit-of-the-doubt and all that. If people don't want others getting credit for work they don't do, they should reveal their vote!

> The reputation they gain if they were rated a '1' would be '-1' and the penalty therefore '-0.5'? That's the same as the current implementation right?

Sort of. My point is, this new scale is not linear - as I have defined it here, there is no equation of the form `y=mx + c` that takes the rating (x) and outputs the factor used to determine the reputation. The old scale was linear (i.e. of the above form) so you could just subtract 0.5 from the rating, and everything would work out. Because it is not the case here (and we want this not-reveal penalty to have the same effect whether you were awarded a '3' or a '2' or a '1'), I think needs to be separate.

**Comment by sekl** [comment]
I'll work on this. :)

**Comment by sekl** [comment]
A few questions:

- Since there is no 0.5 point penalty anymore for ratings, should they still be stored as multiples of 10?
- If no rating is given by eg. the worker, their own rating that they received remains unchanged and instead there is a separate reputation penalty (half as severe as if they had been rated 1), correct?
- Similarly, if neither manager nor worker has submitted a rating, they both receive a 3 and a separate reputation hit?

Probably best if I update the whitepaper first so you can see if my understanding is correct before I start implementing anything.

**Comment by elenadimitrova** [comment]
Since we'll be doing reputation penalties and not rating penalties I guess we no longer need the one decimal point precision on ratings. Your other two points are correct but @area can confirm.

**Comment by area** [comment]
I agree with Elena, we do not need the extra factor of ten any more, and your other statements are also correct.
