### ISSUE TITLE
Allow colonies to be created with existing tokens

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#160]
As it stands, when a colony is created, a new token is deployed alongside the colony. This should be optional, with the alternative being that the creator provides the address of (what is presumed to be) an ERC20 token, that is then used as the colony's own token. If the address passed to the `createColony` function is `0x0`, a new token contract is deployed, as happens currently.

If the supplied contract is not an ERC20 token, things will break in fun and exciting ways - that is unavoidable, and mitigating that should be considered outside the scope of the PR that implements this issue.

**Comment by lazoviccorp** [comment]
I will take this one.

**Comment by lazoviccorp** [comment]
Just one question. Wouldn't it be simpler if we just passed token address, and move the token creation logic outside of `createColony` function?
I know that creating token inside `createColony` will guarantee that token is ERC20, but we still need to make some kind of check for other tokens.
