### ISSUE TITLE
Recovery mode for contracts

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#18]
### 2.2 Contract security

At launch, colonies will be able to be put into a ‘recovery mode’. In this state, whitelisted
addresses are able to access functions that allow the state of the contract to be directly edited — in
practise, this will correspond to access to the functions to allow setting of variables, as well as being
able to upgrade the contract. With the agreement of multiple whitelisted addresses, the contract
will then be able to be taken out of recovery mode once the contract has been returned to a rational
state. Removal from recovery mode requires the approval of multiple whitelisted addresses.

Any approvals from whitelisted addresses to leave recovery mode must be reset whenever a
variable is edited. A whitelisted address agreeing to leave recovery mode records the timestamp at
which the agreement occurred, and any change of variables also update a timestamp indicating the
last edit. When attempting to leave recovery mode, only agreements made after the last edit are
counted towards meeting the threshold.

The first whitelisted address is added at colony creation and is the creator of the colony.
Whitelisted addresses can be added or removed by a simple majority vote of existing whitelisted
addresses.

**Comment by kronosapiens** [comment]
In conversation with @area, the requirement for majority voting to amend the whitelist is removed for now -- the owner will be the one who manages the whitelist.

Also, it should not be possible to edit timestamps (perhaps in general, but specifically the last edit time and agreements to leave recovery mode)
