### ISSUE TITLE
Reconsider CheckErrorRevert / CheckErrorAssert / CheckError implementations

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#187]
Currently, we have three methods used for checking that a transaction (passed as a promise) fails without breaking everything. `CheckError` is the bulk of the implementation, and `CheckErrorRevert` and `CheckErrorAssert`are convenience functions that call `CheckError` and determine whether we expect 'all' gas to be used (where the inverted commas indicate accommodation of `EtherRouter`'s behaviour).

* Do we even care about the type of error that got thrown? Is just checking the status code adequate for our purposes?
* Can we be more specific about the behaviour we expect, rather than just allowing all calls expecting an `assert` to be within 73000 gas? In theory, we could `getCode` and check it's a match for EtherRouter before allowing that margin...

**Comment by elenadimitrova** [comment]
@area are you happy for me to close this in favour of https://github.com/JoinColony/colonyNetwork/issues/201 to resolve the first bullet point and the second one being potentially no longer relevant?

**Comment by area** [comment]
Sure.
