### ISSUE TITLE
Bottleneck with a single task change nonce per colony 

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#192]
A single `taskChangeNonce` per Colony means only a single task change can be open at any one time as this value is used in the signed transaction. 

In a way of solving this limitation, we'd likely need to make this task specific. Also @area had an idea of letting the task role users increment that.

**Comment by filiplazovic** [comment]
Working on this, along with #193 and #188

**Comment by elenadimitrova** [comment]
Oh I picked this up yesterday @filiplazovic (we normally assign ourselves to the task to show it's taken)

**Comment by elenadimitrova** [comment]
#188 is not ready yet for building as the event definitions need to come from the ddb and FE teams

**Comment by filiplazovic** [comment]
Oh man, then it will be just #193
