### ISSUE TITLE
Add contract error messages

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#201]
With the introduction of return error messages for `revert` and `require` failures in `solc@0.4.23` (as upgraded in #198) we need to format and populate those message strings in contracts. There are >100 instances where this is required which in itself warrants a dedicated backlog item here.

Additionally after tooling to support these error messages in JS is introduced, tests have to be refactored to check expected error is returned as wired in `todo` here: https://github.com/JoinColony/colonyNetwork/blob/develop/helpers/test-helper.js#L85

**Comment by elenadimitrova** [comment]
After #288 is merged we should be able to complete this work

**Comment by KevinLiLu** [comment]
I'd like to take on this monster as it will get me familiar with more of the codebase.

**Comment by elenadimitrova** [comment]
Thanks @KevinLiLu 
I have pushed in #288 updates you'll need for this, specifically the `test-helper` change to check `reason`
https://github.com/JoinColony/colonyNetwork/pull/288/files#diff-cfe0340d8acf7ab0683cf395091cd627R97

#288 still is a little rough but should allow you to start working on this reasonably smoothly.

**Comment by area** [comment]
A few thoughts:

Error messages should all start with `colony-` to help users identify where errors are coming from, in the event a transaction touches many different contracts.

All tests that check that a require is triggered correctly should check the 'right' require has been triggered. This includes mining tests in `colony-network-mining.js`, which currently don't use `checkErrorRevert` for a lot of tests that just use `accommodateChallengeAndInvalidateHash`. To make things trickier,  that function just swallows the error, which is generated in different places in that function, depending on what is being tested. If that proves too tricky (there is quite a steep learning curve on those tests), do say so.

**Comment by elenadimitrova** [comment]
Also in the next version of `solium@1.1.8` https://github.com/duaraghav8/Solium/releases/tag/1.1.8 they have introduced `error-reason` ruleset which ensures error messages are provided for revert() and require() statements. Maybe @filiplazovic can upgrade to that disabling the single rule that you can switch on at the end of this work?
