### ISSUE TITLE
Task cancellation

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#22]
### 4.1 Tasks
If no worker has been assigned to a task, the manager has the ability to cancel the task entirely.

Any funds that have already been assigned to the task are assigned to the domain that the task was created in.

**Comment by sekl** [comment]
I'll look through the contracts and work on this task over the next few days, if nobody else has picked it up yet. :)

**Comment by elenadimitrova** [comment]
Sure! :) Note that the basic task cancellation was done in #105 and for the MVP we're not doing tokens staking on task creation (so no stake refunds needed yet here) so just focus on :
>Any funds that have already been assigned to the task are assigned to the domain that the task was created in
