### ISSUE TITLE
Task completion and rating

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#24]
### 4.1 Tasks

After the task has been assigned, the worker may make a ‘final submission’, which includes some
evidence that the work has been completed.
Once the due date has passed or the worker has made their submission, the evaluator may rate
the work. Regardless of whether the rating is positive or not, the task enters a state in which
objections to the final state of the task can be made and disputes can be initiated (see Section
9). Once three days have elapsed, no more objections or disputes can be raised. Once all pending
disputes related to the task are resolved, the parties involved get punished or rewarded based on
the final state of the task.
If the evaluator’s rating for the work is changed as a result of a dispute, they get a reduced payout
based on the discrepancy between their original score and the score that their peers determined to
be more appropriate. If an objection has determined the manager or evaluator should be punished,
they lose their stake, otherwise the stake is able to be reclaimed. The worker is paid based on the
final score awarded to their work, taking into account the result of any disputes.

**Comment by elenadimitrova** [comment]
@lazoviccorp working on adding the task payouts logic to do with task work being rejected or accepted based on the rating of the worker

**Comment by kronosapiens** [comment]
Closing -- this functionality was completed in #166
