### ISSUE TITLE
Add `isGlobalSkill` flag to the ColonyNetwork.getSkill call

### ISSUE THREAD

**Issue by chmanie** [JoinColony/colonyNetwork#249]
## Summary
As per chat with Alex we thought it'd be great to not have to call the `isGlobalSkill` function but get this information in the call of ColonyNetwork.getSkill already (a flag basically stating `true`/`false`).

**Comment by KevinLiLu** [comment]
@chmanie Can I work on this?

**Comment by elenadimitrova** [comment]
Sure @KevinLiLu :)
I'd be interested if we can start returning structs out of functions. This should be possible with the ABIEncoder2 experimental feature.

**Comment by KevinLiLu** [comment]
@elenadimitrova Awesome, thanks!!! 😄
