### ISSUE TITLE
Token Supplier

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#25]
### 5.1.1 Token Generation and Initial Supply

When a colony is created, the `TokenSupplyCeiling` and the `TokenIssuanceRate` are set. The former is the total number of colony tokens that will be created and the latter is the rate at which they become available to the colony-wide domain to assign to tasks or subdomains. The number of tokens available to the colony-wide domain can be updated at any time by a transaction from any user.
At colony creation, some tokens must also be assigned to addresses to allow users to stake tokens to create the first tasks. A one-off lump sum may also be created and made available to the colony-wide domain.

### 5.1.2 Increasing the TokenSupplyCeiling
It is crucial that new tokens cannot be generated without widespread consensus — especially if
tokens have a financial value. Consequently, such decisions require a vote with high quorum and
majority requirements involving both the token holders and reputation holders.

### 5.1.3 Changing the TokenIssuanceRate
The TokenSupplyCeiling represents the tokens that the token holders have granted to the colony
in order to conduct business: to fund tasks and domains, and to hire workers and contributors.
This is especially important during the early life of a colony when it has little-to-no revenue in other
tokens to fall back on.
The TokenIssuanceRate controls how rapidly the colony receives the new tokens. If the rate
is ‘too high’, tokens will accumulate in the pot of the top-level colony domain (or other pots lower
in the hierarchy); usually this is not a big problem. If the rate is too low, this signals that the
colony has a healthy amount of activity and that the issuance rate has become a bottleneck. In
such situations it may be desirable to increase the rate of issuance without necessarily increasing
the maximum supply.
Increasing and decreasing the TokenIssuanceRate by up to 10% can be done by the reputation
holders alone and this action can be taken no more than once every 4 weeks. Larger changes to the
issuance rate should additionally require the agreement of existing token holders.

**Comment by filiplazovic** [comment]
> At colony creation, some tokens must also be assigned to addresses to allow users to stake tokens to create the first tasks. 

I think this is covered by `bootstrapColony`.

> A one-off lump sum may also be created and made available to the colony-wide domain.

Is there specific amount?

**Comment by area** [comment]
> I think this is covered by bootstrapColony.

I agree

>> A one-off lump sum may also be created and made available to the colony-wide domain.
> Is there a specific amount? (Or maybe it should be passed in createColony. It should be different for every token, depending on value of that token?)

No specific amount, but passing in during `createColony` seems okay. It could also be a function only allowed during the bootstrap phase. Note that not all colonies will want to use this functionality, or even be able to, if the token doesn't have `.mint()` or they don't have the permission to call it.

**Comment by filiplazovic** [comment]
Ok, so im just trying to understand - Are we limiting the issuance rate because we want to minimize diluting of existing tokens, or we are giving the colony the guidelines to keep their finances healthy, or there is entirely different reason?

The reason i asked this is because i can also put the functionality for this controlled influx into `claimColonyFunds`, and it will be applied to every colony without exception. `mintTokens` can be easily bypassed.
