### ISSUE TITLE
Allow for additional task properties to be specified during creation

### ISSUE THREAD

**Issue by ConnorChristie** [JoinColony/colonyNetwork#251]
## Summary

It would be nice if there was a way to set the due date when creating the task since right now it requires human (multi)signatures to perform that action.

## Expected Behavior

Allow specifying additional properties for a task upon the `makeTask` call.

## Current Behaviour

The `makeTask` call only accepts a specificationHash and domainId right now and the dueDate can only be changed through a txn signed by a human, contracts are unable to change it.

## Possible Solution

Add optional parameters to the makeTask signature to allow for setting additional properties at the time of task creation.

## Context

I am having multiple individuals working on the same task and I want the author to be able to assign the due date instead (without multisig). I am also using an external contract to facilitate the multiple parties and as of now, the contract itself is unable to set the due date and has to ask the author to set it instead.

**Comment by KevinLiLu** [comment]
@elenadimitrova @ConnorChristie 

I'd like to take this issue. Let me know if there are any conflicts.

### Possible Implementations:

**(1) Use optional parameter**

This would likely be the best solution however optional parameters do not seem to exist in Solidity yet [solidity/#232](https://github.com/ethereum/solidity/issues/232).

**(2) Overload method with additional one that takes in `uint256 _dueDate`**

We would have two methods:
- `function makeTask(bytes32 _specificationHash, uint256 _domainId) public`
- `function makeTask(bytes32 _specificationHash, uint256 _domainId, uint256 _dueDate) public`

Ideally, the second method would call the first method and then call `setTaskDueDate`.

**(3) Make `uint256 _dueDate` a required parameter with a zero value representing unset**

Function declaration would be:
- `function makeTask(bytes32 _specificationHash, uint256 _domainId, uint256 _dueDate) public`

We can do a explicit check `if (_dueDate > 0)` before setting the Task's due date so that passing in a zero value for `_dueDate` will not set the due date (how the current function operates).

<br>

Additionally, should we add a requirement that you cannot call `setTaskDueDate` with a `_dueDate` in the past (if this has not been implemented already)?

**Comment by elenadimitrova** [comment]
Function overloading is cleanest however I'm not sure it's supported (yet) in truffle, details below:
https://github.com/trufflesuite/truffle/issues/737
https://github.com/trufflesuite/truffle/issues/569

Can you test this option and if it fails perhaps explore the darq-truffle solution suggested in 737 above?

**Comment by KevinLiLu** [comment]
@elenadimitrova I'm getting a weird error when running tests:

```
Running migration: 4_setup_colony_version_resolver.js
  Running step...
  ... 0x3bc0613d21bfa62290e77604a1d1e26c9ef3dd312eaeceba44fbca7310222357
  ... 0xa2e4d3154afcd52060606c8b2fa7fd5988c3d94560e77577c3dae810ad3fb973
  ... 0x0e3b3d6bc66a335ba5bea78fb1d372d68e754be1e413bb6a727e5b7a75bff56e
  ... 0x17d09afce681f2b9f300f42fee8d34a4a436188dba4b80c39b0f818b65b21f8c
What are you doing!? Defining functions with the same name in different files!? You are going to do yourself a mischief.  You seem to have two  makeTask  in  ColonyTask and  0xf812b58b7c9c99c67af0cbd973e071a8fd2fdd3e
error Command failed with exit code 1.
```

It seems to be coming from https://github.com/JoinColony/colonyNetwork/blob/81519ed8b65ae5d79cdf15e882e1bb392c4057cf/helpers/upgradable-contracts.js#L5.

Any idea on what to do here?

**Comment by elenadimitrova** [comment]
Interesting.. I added an experimental `darq-truffle` branch and that builds successfully https://circleci.com/workflow-run/128b69f2-07f5-4c72-8645-016070092ced 

Atm trying to get function overloading working there.

**Comment by elenadimitrova** [comment]
`truffle@next` which is the upcoming Trufflev5 includes a version of `truffle-contract` that uses `web3v1` which supports overloads. I'll work on upgrading us to v5 but may take some time (best case a few days, worst case a few weeks). I suggest we hold off doing this until then or alternatively use web3-abi to manually compose and send transactions for the overloaded function, leaving a todo to refactor that when v5 is available.
Note: We'd need to upgrade to v5 anyway for many more reasons than just overloading.

**Comment by elenadimitrova** [comment]
However, feel free to work on the overloaded function and additionally fixing the `upgradable-contracts` `parseImplementation` function which I've fudged here to get overloaded functions registered in the colony `Resolver` https://github.com/JoinColony/colonyNetwork/commit/bc93151bae0bac81adb3e597bbf453c24ac9674a

**Comment by KevinLiLu** [comment]
That's fine. If we are not in a rush to push out this enhancement (basically MVP token sale I guess), then I think it is best to just wait and allocate the dev time in other issues.

**Comment by ConnorChristie** [comment]
If you’d like, I could spend time to work on this issue!

**Comment by KevinLiLu** [comment]
@ConnorChristie It's all yours my friend!

**Comment by elenadimitrova** [comment]
You could now rebase on top of #288 to enable testing your overload already. Note that that is still largely WIP waiting of an update where BigNumber is again out of functions returning a number.

**Comment by elenadimitrova** [comment]
@ConnorChristie it appears the amount of permutations we'll need for `makeTask` is pointing to a different design direction than overloads. The product team will need an option of setting a combination of talk properties during the task create phase in addition to the mandatory `specificationHash` and `domainId`: `dueDate`, `skillId` as well as payouts for all 3 roles.
After a conversation with @area we thought the best option to cater for all these is extending the `makeTask` to accept these new uint parameters with 0 meaning they are unassigned.
Hopefully this makes sense and you're not upset by the late requirements change (I know I normally am) :)

**Comment by ConnorChristie** [comment]
@elenadimitrova Haha no worries (I have yet to start on implementing this). I knew there was going to be more than just the initial thought of adding multiple overloads. I appreciate the design and requirements presented and will start working on this later today :)

**Comment by elenadimitrova** [comment]
Also obviously with this approach you don't need truffle v5 so feel free to just base it off `develop`.

**Comment by ConnorChristie** [comment]
@elenadimitrova What do you mean by:
> setting a combination of talk properties

What are "talk properties"?

**Comment by elenadimitrova** [comment]
Sorry @ConnorChristie , I meant "**task** properties"

**Comment by elenadimitrova** [comment]
Hi @ConnorChristie this item is included in current Sprint 6 and will have to be done in the next 2 weeks at most. Let us know if that's a problem. In theory there should be ~half a day's work at most here so if you face issues let us know.
