### ISSUE TITLE
Changing the TokenIssuanceRate

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#27]
### 5.1.3 Changing the TokenIssuanceRate
The `TokenSupplyCeiling` represents the tokens that the token holders have granted to the colony
in order to conduct business: to fund tasks and domains, and to hire workers and contributors.
This is especially important during the early life of a colony when it has little-to-no revenue in other
tokens to fall back on.
The `TokenIssuanceRate` controls how rapidly the colony receives the new tokens. If the rate
is ‘too high’, tokens will accumulate in the pot of the top-level colony domain (or other pots lower
in the hierarchy); usually this is not a big problem. If the rate is too low, this signals that the
colony has a healthy amount of activity and that the issuance rate has become a bottleneck. In
such situations it may be desirable to increase the rate of issuance without necessarily increasing
the maximum supply.
Increasing and decreasing the `TokenIssuanceRate` by up to 10% can be done by the reputation
holders alone and this action can be taken no more than once every 4 weeks. Larger changes to the
issuance rate should additionally require the agreement of existing token holders.

**Comment by filiplazovic** [comment]
I will start off with creating a function `setTokenIssuanceRate(uint256 _amount, uint256 _interval)` where `_amount` is amount of tokens per `_interval` (in seconds).
This function can be called once every 4 weeks. There will be a formula to calculate how much the rate is changed, and allow only bellow 10%.

Constrains will be added in `claimColonyFunds` where we will calculate how many tokens are available for claim by subtracting `now` with `lastClaimTimestamp` which is sum of all claimed intervals.

**Comment by elenadimitrova** [comment]
Just to bring the conversation had with @area here.
For the purposes of the MVP, the requirements are changed slightly in that the colony owner should be able to arbitrarily change the ceiling and issuance rates. 

Although this is currently the case for the `TokenSupplyCeiling`, the `TokenIssuanceRate` has this enabled for an owner, but limited to:
- changes being done at most once every 4 weeks
- rate difference between the current and new, whether increase or decrease can be up to 10%  

There is an additional requirement in the white paper (see last sentence in issue above) that we haven't fulfilled yet, which is:
>Larger changes to the issuance rate should additionally require the agreement of existing token holders

which I argued will be good to implement as well with the same owner-only permission. @area however is hesitant to merge both functions in and have them both 'on'.

Another thing I considered is setting the `TokenIssuanceRate` to the max `uint128` which should get that limit out of the way for minting tokens, similarly to how we'd deal with the `TokenSupplyCeiling`.

**Comment by kronosapiens** [comment]
Rolling into #25
