### ISSUE TITLE
Account for tokens being able to burn their supply during payouts

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#272]
If a token being used by a colony allows its tokens to be burned, altering its total supply, then the reward payouts will be effected which could lead some people short-changed depending on when they claimed their rewards relative to the burn. To avoid this, reward payouts should save the total token supply in the same way they save the current reputation state, and that figure should be used for the duration of the payout, regardless of what the current total supply is.

**Comment by filiplazovic** [comment]
Aren't we doing this [here](https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyFunding.sol#L176)?

**Comment by area** [comment]
*Sigh*

Yes.

**Comment by elenadimitrova** [comment]
But doesn't this `require` check mean that reward payouts cannot be started if tokens were burned meanwhile?  https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyFunding.sol#L177

**Comment by filiplazovic** [comment]
It will throw if colony holds all of the token supply or when supply is `0`.
