### ISSUE TITLE
Fix parent reputation updates

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#282]
## Summary

Okay, so, during a dispute over a parent reputation update, the 'correct' skill ID is looked up by this line: https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ReputationMiningCycle.sol#L609

This line looks very similar to the (correct) line for child skill updates. However, the array that reads from only contains parents that are powers of two away from the skill in question ( https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyNetwork.sol#L199 ).

The difference only manifests when you have four generations of skills, which none of the tests do yet, and the client is wrong in the same way, so such a test would pass currently, but not all the required skills would be present int he reputation tree.

The easiest fix would seem to be to implement a function on colonyNetwork that returns the nth parent of a skill, if present, rather than the nth entry in the parents array. A loop over the binary representation of 'n' seems like the easiest way, moving up the tree based on which bits are '1', but I'd be open to other suggests.

It is possible that function should replace getParentSkillId, rather than be implemented alongside it. If the knock-on consequences weren't too big, I think that would avoid us getting tripped up by this in the future.

At the minimum, a test should be included that demonstrates that when a skill is updated, *all* of its parents are if it has at least three parents, and a test that shows when a parent that is not a 2^n parent is disputed, the dispute resolves correctly.

**Comment by filiplazovic** [comment]
Do you wish to work on this? It would be a nice place to start with reputation stuff for me

**Comment by kronosapiens** [comment]
Ah I was going to work on it, but if you'd like to then feel free!

**Comment by filiplazovic** [comment]
I will leave it to you, there is plenty of stuff for me

**Comment by kronosapiens** [comment]
👍
