### ISSUE TITLE
Return structs in read functions

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#283]
With the experimental ABIv2 we can return Structs out of function calls (as well as pass those in). It it worth exploring as a design in our contracts potentially with the following benefits:

- Enforces return data structures to comply with those declared in storage. This was the reason behind the misalignment highlighted in `getSkill` return value issue here  https://github.com/JoinColony/colonyNetwork/issues/249
- Simplifies upgrades as extending a struct (e.g. adding a new member) won't necessitate upgrade of the function return parameter type - subject to testing

Candidates for this refactoring are essentially all getter functions where a struct is returned: `getSkill`, `getTask`, `getDomain`, `getTaskWorkRatings`, `getTaskRole`, `getRewardPayoutInfo`, `getUserLock` etc

**Comment by filiplazovic** [comment]
I encountered some strange error when i tried to used `ABIEncoderV2` in `ReputationMiningCycle`. After a little research i found out that creating a new instance of a contract with `pragma experimental "ABIEncoderV2"` in it costs ~300k gas more. I will investigate on this a little bit more and update you if i find more info
