### ISSUE TITLE
Reputation by Domain

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#29]
### 6.1.1 Reputation by Domain
The hierarchical structure of a colony was described in Section 4.2. Reputation is earned in this hierarchy, and a user has a reputation in all domains that exist — even if that reputation is zero. When a user earns or loses reputation in a domain, the reputation in all parent domains changes by the same amount. In the case of a user losing reputation, they also lose reputation in all child domains. When reputation is lost in a domain with children, all child domains lose the same fraction of reputation. If a reputation update would result in a user’s reputation being less than zero, their reputation is set to zero instead.
An example makes this clearer. Suppose a colony has a ‘development’ domain which contains a ‘backend’ domain and a ‘frontend’ domain, as in Figure 1 on page 10. Any time a member of the colony earns reputation for work completed in the backend domain, it will increase their backend reputation, their development reputation and their reputation in the all-encompassing top-level domain of the colony. Reputation earned in the development domain will only increase the development and top-level domain reputation scores of the user.
Later, the user behaves badly in the ‘development’ domain, and they lose 100 reputation out of the 2000 they have in that domain. They also lose 100 reputation in the parent domains, and 5%
(100/2000) of their reputation in each of the child domains of the ‘development’ domain (which in this example, includes all of the Frontend, Backend, Node.js and Ruby domains).

**Comment by elenadimitrova** [comment]
Just to be clear what happens when a reputation change is negative and the current value either doesn't exist or is `0`? Does that mean that child reputation updates are `0` or they equal the full reputation lost?

**Comment by area** [comment]
The child reputation updates will be 0, and any reputations that don't currently exist in the state will be created.
