### ISSUE TITLE
Refactoring task update calls

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#296]
Due to the number of transactions required in a task lifecycle and the granular approach we've taken in the contract design vs product design we'd like to look for opportunities to pull some actions together into a single function call and therefore a single transaction interaction in the UI. Below is the initial set of ideas for what can be bundled but more could come of of the refactoring if opportunities are found:

- Setting the evaluator to the task creator (similarly to how the manager is assigned) as for the Colony Contribute these 2 roles will be fulfilled by the same person. We'll still allow for the role to be reassigned later
- Submitting the deliverable and rating for the task manager. If they are submitting the task, the immediate next thing they need to do is rate the manager
- Changing task role assignments currently requires `removeTaskXRole` followed by `setTaskXRole`, perhaps these can be part of the same call?
- Public functions `assignWorkRating` + `finalizeTask`?

#251 is already going to handle the `makeTask` changes to allow in addition to the mandatory `specificationHash` and `domainId` to also set the `dueDate`, `skillId` as well as payouts for all 3 roles

**Comment by collinvine** [comment]
Thanks for diving into this, @elenadimitrova.

One thing I didn't understand was about possibly bundling `assignWorkRating` and `finalizeTask` together.

I thought that part had to linearly move through these phases:

Rate > Reveal > Finalize

If we were to bundle rate and finalize, what'd that do with Reveal? Would that also be bundled somehow?

**Comment by itspatch** [comment]
Yes thanks @elenadimitrova! Do you have about a time estimate when you might get to this? 

We are planning on doing a design mini sprint around the task creation process and task rating process once these questions are answered to try to come up with the best user experience possible. Having clarity on these questions would be helpful.

**Comment by collinvine** [comment]
@elenadimitrova I didn't quite understand that. I read the description, but still not sure about the linearity of these calls. 

Can finalize be called before reveal? 
Would reveal also be bundled with rate and finalize?

**Comment by elenadimitrova** [comment]
@collinvine `assignWorkRating` is called only if rate/reveal wasn't completed in the time provided. This is to populate the respective users with the relevant ratings, e.g. if a worker hasn't rated a manager the manager gets `3` and worker rating is penalised. So essentially it gets called to ensure ratings are complete, e.g. it is not an explicit task member action. Perhaps it might be permanently merged into the `finalizeTask` logic as it is a safety function in a way, different to the `submitTaskWorkRating` and `revealTaskWorkRating` that users normally call.

**Comment by itspatch** [comment]
@elenadimitrova let me know if you have any updates on this. We'll use that information to finalize our task workflow designs early next week.

**Comment by elenadimitrova** [comment]
@kronosapiens is working on this atm. He's done with the first two suggestions I think and was last deliberating on whether we can do that third suggestion on merging removeTaskXRole and setTaskXRole, which I am leaning towards _not_ doing.

**Comment by itspatch** [comment]
ok, thanks. @kronosapiens let me know if you have any other updates. We'll move forward in product with this current understanding.

**Comment by kronosapiens** [comment]
@itspatch Yup. I should be able to get these optimisations out the door quite soon. Blending the unassign-reassign roles functions will require a little more work. You can follow the progress here: https://github.com/JoinColony/colonyNetwork/pull/309

**Comment by elenadimitrova** [comment]
@itspatch I am still unconvinced we should merge the unassign/assign roles into 1 which needs 3 signatures i.e old worker, new worker + manager. Logically these 2 steps seem distinct to me even compared to the real world cases of say terminating a contract with one person and hiring another.

**Comment by collinvine** [comment]
@elenadimitrova I agree, and that's how it is in the beta and I think it's totally fine.

**Comment by itspatch** [comment]
Agree with Collin. That is ok, we might need your help figuring out the best way to show transactions that are in sequence on the UX, but we will tackle that in the future. Thanks for checking in with that.
