### ISSUE TITLE
End to end task lifecycle review

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#338]
Go over the task lifecycle functions, perhaps even document them here for posterity https://docs.google.com/spreadsheets/d/1HiL-jJd22BzX4aAMVaOv0ptYkBfnkfY4yhJkLAHVOGI/edit#gid=0 and fix any gaps that may break the cycle.

Solving the todo here https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyTask.sol#L589
is also part of this work.

```
// TODO: Check if we are changing a role before due date and before work has been submitted
function setTaskRoleUser(uint256 _id, uint8 _role, address _user)
```

Also the following:
- cancelling a task after a deliverable is submitted should not be possible

**Comment by eccheung4** [comment]
I was able to cancel a task after a deliverable was submitted. Not sure, but I think a manager shouldn't be able to cancel a task once a deliverable is submitted.

**Comment by elenadimitrova** [comment]
Yes you're right @eccheung4. Adding this to the list above.
