### ISSUE TITLE
Review reputation mining submission window duration

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#356]
Currently this is set to 1 hour and we should consider to increase that to at least 24 hours

**Comment by kronosapiens** [comment]
I am curious what the intended tempo is for ongoing colony activities (reputation mining, meta colony token minting, etc).

**Comment by elenadimitrova** [comment]
For token minting we had implemented token supply ceiling and token issuance rate levels as defined in the white paper in colonyNetwork#289 but that won't be released in the first version of Colony Contribute which is why that's on hold

**Comment by elenadimitrova** [comment]
For the others, based on the usage in the Colony Beta, which is the closest field test we have in reality, Colonies were closing ~100 tasks per month, meaning ~100 reputation update log entries to process per month. Maybe that helps answer some of your other questions.

**Comment by kronosapiens** [comment]
After some thinking and discussion, it seems like the main considerations are:

- Variability in mining rewards (smaller window is better)
- Reward covering maximum gas costs (bigger window is better)
- Being able to detect and stop malicious activity (bigger window is better)

At minimum the window should be large enough that the reward would cover the gas costs involved in defending a submission against a malicious mining attack, or approximately 2000 CLNY. If not, malicious miners could making mining uneconomical relative to the reward, even if the false hashes are correctly discarded. Note that #352 may help us here, if we choose to send the stake of malicious miners to the good miners (in that case, we could pay for the defense out of the lost stake, rather than out of the reward pool).

**Comment by kronosapiens** [comment]
So regarding mining rewards and the issue of having the reward at *minimum* cover the gas cost (and using that answer to help us decide what the mining window should be), I've arrived at this:

```
100m CLNY / year
100m / 4 = 25m for rewards
25m / 8760 hours = 2800 CLNY per hour
```

Now, if we use malicious miner stake to compensate miners for defending their submissions (https://github.com/JoinColony/colonyNetwork/issues/352#issuecomment-431041848), then the stake will more than compensate miners for the defense. So the net gas cost for miners (excluding defense) is 1m, or about ~0.02 ETH. Let's say that this is less than 100 CLNY.

So we have 2800 CLNY per hour to share amongst 12 miners, each with a different reward weight. Assuming a max/min weight ratio of 4:1, this would work out to the top miner receiving ~360 CLNY, and the bottom miner receiving ~105 CLNY. So the smallest reward is still larger than the gas cost associated with mining -- all miners who submitted a hash are incentivized to participate in the mining process.

So, one-hour mining windows will allow for a large enough reward to cover gas costs. Note though that this involves a *minimum* reward which is fairly close to the 25% target, meaning miner relative reputation will increase more quickly in the case of minimal work in the meta colony (i.e. even if there is no other activity in the meta colony, we will still be paying out about 25% of CLNY minting to miners). Ideally, the minimum reward would be much less, perhaps 1-5% of inflation. A larger mining window could achieve this.

**Comment by kronosapiens** [comment]
Whoops fat finger.

**Comment by kronosapiens** [comment]
Given that at the beginning, the mining client is new software which needs to be battle tested, and there will be (relatively) fewer miners, I would say a 24 hour mining window would be best to give the most flexibility in catching and fixing problems before they can have downstream affects.

Once the software matures and the number of miners increases, I would suggest we decrease the mining window to 1 hour to reduce the variability of mining rewards (and thus make the reputation amongst miners more uniform).
