### ISSUE TITLE
Rename the 'owner' role

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#369]
DSAuth has it's own concept of an `owner`, which is the one person that can call any function. For Colonies, there is a role in DSRoles we're calling owner, which isn't a superuser (indeed, we make sure [there is no such user](https://github.com/JoinColony/colonyNetwork/blob/58c3ea1d46f9492807bf9bc041da6aec2145e748/contracts/ColonyNetwork.sol#L150). This is going to trip us up at some point if we don't rename the role in DSRoles...

**Comment by elenadimitrova** [comment]
After [some internal discussion](https://joincolony.slack.com/archives/C0YNG3M8B/p1542136779196700) we'll be renaming Colony `owner` to `founder`
