### ISSUE TITLE
Destructing a Token auction can be stalled

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#377]
If someone sends CLNY to an auction contract (outside of taking part in the auction, after the auction has ended), then [this `assert`](https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyNetworkAuction.sol#L214) will never pass meaning the auction will never be able to `destruct`.

**Comment by area** [comment]
'Bug' is probably accurate, but scarier than it should be. This doesn't have a knock-on effect on the colony network - doesn't get the dust from rounding errors returned to it at the end of the claims process, but that's it. The auction works as intended, users can claim the tokens they've paid for, and the metacolony gets the CLNY used in the auction.

**Comment by blockchain-doppelganger** [comment]
> If someone sends CLNY to an auction contract (outside of taking part in the auction, after the auction has ended), then [this `assert`](https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyNetworkAuction.sol#L214) will never pass meaning the auction will never be able to `destruct`.

Why you create issues, are you Colony Solidity developer? I thought you must fix this problem

**Comment by elenadimitrova** [comment]
We log issues we find first, then we fix them.
