### ISSUE TITLE
Earning reputation from contributing to a task by Evaluator

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#38]
### 6.2.1 Reputation change from contributing to a task
Upon completion of a task, the evaluator also earns reputation based on their token reward. 

For the purposes of calculating earned reputation the rating of the evaluator is assumed to be the same as the maximum of that of a manager, i.e. 5.

There is no explicit rating of the evaluator, but as with all other payments and rewards, an objection
can be raised before a payout occurs; if the evaluation is changed by such an objection, the evaluator’s reward is reduced or turns in to a loss of reputation.

**Comment by kronosapiens** [comment]
This functionality has been implemented (see #158)
