### ISSUE TITLE
Update dappsys libraries

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#382]
I've spoken with dapphub guys to update the [dappsys-monolithic](https://github.com/dapphub/dappsys-monolithic.git) library to include error messages. This issue is to track that work as we should update as well as these failures are the only ones untested explicitly atm.

**Comment by kronosapiens** [comment]
Noting that these changes have been pushed to `https://github.com/dapphub/dappsys-monolithic`, you can update by running:

`git submodule update --remote`

@elenadimitrova @area
