### ISSUE TITLE
Potential overflow in reputation calculation on task payout

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#394]
When calculating reputation earned on a task in `ColonyTask.getReputation`, there is a potential overflow as that uses a multiplier of the task payout which is a `uint256` and the rating multipliers which can go up to `1.5` meaning the following calculation there will throw
```
reputation = SafeMath.mulInt(payout, ratingMultipliers[rating - 1]);
```
https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyTask.sol#L484

**Comment by kronosapiens** [comment]
Noting that we have a test which explicitly checks for this behavior:

```
    it("should revert on reputation amount overflow", async () => {
      // Fund colony with maximum possible int number of tokens
      await fundColonyWithTokens(metaColony, clnyToken, INT256_MAX);
      // Split the tokens as payouts between the manager, evaluator, and worker
      const managerPayout = new BN("2");
      const evaluatorPayout = new BN("1");
      const workerPayout = INT256_MAX.sub(managerPayout).sub(evaluatorPayout);

      const taskId = await setupRatedTask({
        colonyNetwork,
        colony: metaColony,
        token: clnyToken,
        managerPayout,
        evaluatorPayout,
        workerPayout
      });

      // Check the task pot is correctly funded with the max amount
      const taskPotBalance = await metaColony.getPotBalance(2, clnyToken.address);
      expect(taskPotBalance).to.eq.BN(INT256_MAX);
      await checkErrorRevert(metaColony.finalizeTask(taskId), "colony-math-unsafe-int-mul");
    });
```

Do we want to change the spec here? @elenadimitrova @area 

I see an argument for the change, on the grounds that any requires on payouts should be thrown when the payouts are set, not when the task is complete and payouts are being made.

**Comment by elenadimitrova** [comment]
@kronosapiens Your point above is exactly what I think this issue meant. We don't want tasks to be deadlocked because of this behaviour. 
Task payouts can only be changed _before_ the task is completed whereas this issue (of not being able to finalise) will only surface _after_ the task is completed and even rated. We should therefore solve this at the source which, as you suggested, when the task.payout itself is set.

**Comment by kronosapiens** [comment]
It's an interesting one in that there's not a clear best answer. It seems like we'd simultaneously like to avoid deadlock, allow users as much flexibility as possible (w.r.t to setting large payouts), and provide the most intuitive behavior as possible (no unexpected truncation).

I drew some charts last week and fortunately the maximum reputation value can never be more than 1.5x the task payout. Given that `INT256` gives us 255 bits of integer (plus the sign bit), I think its fine to say that task payouts are capped at 254 bits, or 1/4th of the `UINT256` range. That way we avoid deadlocks and truncation at the cost of (an arguably small in practice) flexibility.
