### ISSUE TITLE
Impossible to use OpenZeppelin v1.10 ERC20 Mintable token for Colony

### ISSUE THREAD

**Issue by igorline** [JoinColony/colonyNetwork#405]
# Prerequisites
- [X] I checked to make sure that this issue has not already been filed

## Summary
ColonyNetwork is incompatible with OpenZeppelin v1.10 Mintable ERC20 token due to specifiaction and implementation difference of ownership and minting logic. Specifically, Colony method `mintTokens` is calling Token `mint` method according to dappsys mintable token specification with amount of tokens to mint passed as an argunment. OpenZeppelin mintable token specification `mint` method is receiving address and amount as arguments.

Here are the links for specifications:
https://github.com/dapphub/dappsys-monolithic/blob/master/token.sol#L71
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.10.0/contracts/token/ERC20/MintableToken.sol#L36

I think OpenZeppelin smart contracts library is widely used and actively developed, and should not be ignored by Colony Network.

**Comment by ryanchristo** [comment]
Hey @igorline! Thanks for opening an issue. We will look into this.
