### ISSUE TITLE
Public setStorageSlot funct allow everyone to rewrite any data in contract 

### ISSUE THREAD

**Issue by blockchain-doppelganger** [JoinColony/colonyNetwork#406]
https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ContractEditing.sol

**Comment by ryanchristo** [comment]
Hey @blockchain-doppelganger! Thank you for opening an issue. Please follow the [issue template](https://github.com/JoinColony/colonyNetwork/blob/develop/docs/ISSUE_TEMPLATE.md) when opening a new issue. Could you update the description? Thanks!

**Comment by blockchain-doppelganger** [comment]
@ryanchristo I start read ColonyNetwork whitepaper and it seems interesting. Do you need a Russian Translation of Whitepaper? If yes, contact me doppengalger@tutanota.com

**Comment by ryanchristo** [comment]
@blockchain-doppelganger Yea, the more translations of the whitepaper the better. We also might be setting up some tasks for translation once we go live on mainnet.

What's the status of this issue? Can you update the description using the [issue template](https://github.com/JoinColony/colonyNetwork/blob/develop/docs/ISSUE_TEMPLATE.md)? Thanks!

**Comment by blockchain-doppelganger** [comment]
> @blockchain-doppelganger Yea, the more translations of the whitepaper the better. We also might be setting up some tasks for translation once we go live on mainnet.
> 
> What's the status of this issue? Can you update the description using the [issue template](https://github.com/JoinColony/colonyNetwork/blob/develop/docs/ISSUE_TEMPLATE.md)? Thanks!

I read Colony contracts, and maybe I was wrong. Do you see my another issue, is it correct?

**Comment by elenadimitrova** [comment]
`ContractEditing` is used for testing purposes and can only be temporarily added to new ReputationMiningCycles being deployed when in recovery mode in order to correctly port log entries across. For more information on recovery mode, see implementation in  https://github.com/JoinColony/colonyNetwork/pull/303#issuecomment-426577094
