### ISSUE TITLE
Overflow in main ColonyNetwork contract 

### ISSUE THREAD

**Issue by blockchain-doppelganger** [JoinColony/colonyNetwork#407]
- [x] I checked to make sure that this issue has not already been filed

https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ColonyNetwork.sol
Lines - 
123    skillCount += 1;
160   skillCount += 1;
161   colonyCount += 1;

and other
## Expected Behavior
If the current state of the variable is 2^256. then if we add 1 to it, it will throw the error

## Current Behaviour
If the current state of the variable is 2^256. then if we add 1 to it, it will be 0 (Solidity int overflow)

## Possible Solution
Use SafeMath library, or add require in functions

**Comment by elenadimitrova** [comment]
@area's back of the envelope calculation on this theory suggests that even if you had all of Ethereum's mining power mining transactions for free, focussing on getting just one of those counters to overflow, it would take at least 10**58 times the age of the universe to achieve it.
