### ISSUE TITLE
Bootstrapping reputation (new Domains) 

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#41]
### 6.2.3 Bootstrapping reputation
We note that the same is not required when a new domain is created in a colony. We do not wish to allow the creation of new reputation here, as this would devalue reputation already earned elsewhere in the colony. This bootstrapping issue is resolved by instead using reputation within the parent domain, when a child domain contains less than 10% of the reputation of its parent domain. 
A domain below this threshold cannot have domains created under it.

**Comment by kronosapiens** [comment]
Combined with #28
