### ISSUE TITLE
Integer overflow in ColonyNetworkMining

### ISSUE THREAD

**Issue by Destiner** [JoinColony/colonyNetwork#413]
## Summary
Possible integer overflow at [`ColonyNetworkMining.rewardStakers()`](https://github.com/JoinColony/colonyNetwork/blob/8482e7fceb6ef4aa12c461f0a6df4d6fb869bf09/contracts/ColonyNetworkMining.sol#L131). This is suspicious, because we have `assert` one line above that aims to eradicate int overflow. Therefore the problem here is that we can pass this assert, but still overflow when minting new tokens.

## Steps to Reproduce (for bugs)
Call `rewardStakers` with big number of stakers.

## Expected Behavior
Reward stakers should revert on overflow.

## Current Behaviour
Amount of minted tokens will overflow.

## Possible Solution
More strict assert: `assert(stakers.length * reward < uint256(int256(-1)));`

**Comment by area** [comment]
There are a lot of TODOs floating around this function, and you are certainly correct that the assert there is inadequate for what the comments describe it as doing. That said, I don't believe an overflow is possible. `rewardStakers` is limited to a length of 12 (by [this](https://github.com/JoinColony/colonyNetwork/blob/8482e7fceb6ef4aa12c461f0a6df4d6fb869bf09/contracts/ReputationMiningCycle.sol#L138), and `reward` is hardcoded at `10**18`, and so the maximum value will not overflow. 

I am closing this issue, but if I have overlooked something please feel free to reopen it.

This function is being reworked as part of #399
