### ISSUE TITLE
Wrong signature of bootstrapColony in unit test

### ISSUE THREAD

**Issue by Destiner** [JoinColony/colonyNetwork#414]
## Summary
[This](https://github.com/JoinColony/colonyNetwork/blob/8482e7fceb6ef4aa12c461f0a6df4d6fb869bf09/test/colony.js#L228) test case makes sure that user can't call `bootstrapColony` function. However, this function doesn't match implemented function [`bootstrapColony(address[] _users, int[] _amounts)`](https://github.com/JoinColony/colonyNetwork/blob/8482e7fceb6ef4aa12c461f0a6df4d6fb869bf09/contracts/Colony.sol#L88) (note **int[]** type) and therefore doesn't test the function properly.

## Steps to Reproduce (for bugs)
Run `colony.js` test.

## Expected Behavior
Test should cover implemented function.

## Current Behaviour
Test doesn't cover implemented function.

## Possible Solution
Replace the signature:
`functionSig = getFunctionSignature("bootstrapColony(address[],int256[])");`

**Comment by area** [comment]
You are correct. The guard this test is testing is also tested [elsewhere](https://github.com/JoinColony/colonyNetwork/blob/8482e7fceb6ef4aa12c461f0a6df4d6fb869bf09/test/colony.js#L310), but it should be correct everywhere. Leaving this issue open until it is fixed.
