### ISSUE TITLE
Reputation update log

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#43]
### 6.4 Reputation update log
Whenever an event that causes one or more users to have their reputation updated in a colony occurs, a corresponding entry is recorded in a log in the `ColonyNetwork` contract. Each entry in the log contains:
 - The user suffering the reputation loss or gain.
 - The amount of reputation to be lost or gained.
 - The colony the update has occurred in.
 - How many reputation entries will need to be updated (including parent, child and colony-wide total reputations). This is the motivation for storing `n_parents` and `n_children` for each skill and domain, as described in Section 6.3.
 - How many total updates to reputations have occurred before this one in this cycle, including
decays and updates to parents and children.

If the reputation update is the result of a dispute being resolved (as outlined in Section 6.2.2), then instead of these first three properties, there is a reference to the dispute-specific record of stakes in the relevant colony. For the structure of this log, and an explanation of the way that it allows individual updates to be extracted in constant gas, see Appendix A.

This log exists to define an ordering of all reputation updates in a reputation update cycle that is accessible on-chain. In the event of a dispute during the reputation mining protocol (described in Section 7), the `ColonyNetwork` contract can use this record to establish whether an update has been included correctly.

**Comment by kronosapiens** [comment]
Already implemented
