### ISSUE TITLE
Fix brittle reputation mining test

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#468]
The test `should cope with many hashes being submitted and eliminated before a winner is assigned` has been frequently failing in CI both as part of the [main test suite run](https://circleci.com/gh/JoinColony/colonyNetwork/5382) as well as the [coverage testing](https://circleci.com/gh/JoinColony/colonyNetwork/5404?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

It's slowing down our development pipeline and should be investigated and resolved

**Comment by area** [comment]
Closed by #482
