### ISSUE TITLE
Submission of a new root hash - eligibility calculation

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#47]
### 7.4 Submission of a new root hash
*Who can submit a new root hash?*
All CLNY token holders are eligible to become miners and participate in the reputation update process, but since any user can calculate the correct root hash locally, it would be possible for any
miner to submit the hash to the contract. 
It is however undesirable to have too many submissions for every update. We propose a mechanism
that only allows some miners to submit results to begin with. To participate in the mining process, Common Colony Token holders must stake some of their tokens to become ‘reputation miners’. A submission will only be accepted from a miner if 
```
keccak256(address, N, hash) < target
```
At the beginning of the submission window, the target is set to `0` and slowly increases to `2^256 - 1` after `150` blocks. We limit the total number of miners allowed to submit a specific hash to `12`. The variable `N` that goes into the hash is some integer greater than `0` and less than the number
of tokens the Common Colony Token holder address has staked divided by `10^15`, meaning that users with a large stake have a higher chance of qualifying to submit a hash sooner than smaller stake holders. The factor of `10^15` is introduced to ensure that all hashes a user is eligible to submit can be calculated in a few seconds by the client. It also effectively creates a minimum number of tokens that must be staked to submit a hash. This puts a tangible cost on any attacks revolving around spamming known false submissions (see Section 7.7).
Miners will also be required to have staked their tokens for a few update cycles before they are eligible to submit or support a hash.

**Comment by elenadimitrova** [comment]
@area for colony contribute launch considering the limit on CLNY transfers we probably don't need the remaining logic defined here?, e.g.:
>Miners will also be required to have staked their tokens for a few update cycles before they are eligible to submit or support a hash.

**Comment by area** [comment]
In the cold light of nearly a year later, we can't think of a reason why you need to have staked for a few cycles, just since before the start of the current cycle (to avoid people withdrawing and depositing in a new address that they may be able to submit from earlier). This is much easier to implement, so unless we come up with a reason why you need to have staked for multiple cycles, we're just going to do that.

**Comment by kronosapiens** [comment]
Hi, it is not entirely clear to me what work remains to be done here -- the entry submission code already uses the stake to determine eligibility. If we are omitting the need for a minimum staking period then... ?

**Comment by kronosapiens** [comment]
Noting: this will be implemented by adding a `lastStaked` timestamp to the token locking contract, and updating it whenever a deposit (but not a withdrawal) is made.

**Comment by kronosapiens** [comment]
I would suggest making this issue conditional on #317 as the suite will need to be rewritten to account for minimum staking durations.
