### ISSUE TITLE
Reduce size of ReputationLogEntry

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#496]
This:

```
  struct ReputationLogEntry {
    address user;
    int amount;
    uint256 skillId;
    address colony;
    uint256 nUpdates;
    uint256 nPreviousUpdates;
  }
```

Could be this:

```
  struct ReputationLogEntry {
    address user;
    int amount;
    uint256 skillId;
    address colony;
    uint128 nUpdates;
    uint128 nPreviousUpdates;
  }
```

Which slims the struct down by one word and thus reduces the cost of every update by 20k gas. Assuming there are less than UINT128_MAX (340282366920938463463374607431768211455) updates per cycle we will be ok.

**Comment by dev1644** [comment]
Hi All, Want to ask you question about the contribution. 
Can anyone solve these issues and submit PR?
Will it be accepted?

**Comment by elenadimitrova** [comment]
@dev1644 we accept contributions for all issues. Follow the guidelines [here](https://github.com/JoinColony/colonyNetwork/blob/develop/docs/CONTRIBUTING.md)
Whether it's accepted depends on the quality of the work. Also note we are close to go-live so timelines are shorter than usual. If this becomes pressing to solve, I'll let you know here if you decide to work on it

**Comment by dev1644** [comment]
I am working on this.
