### ISSUE TITLE
Restore good state in reputation mining tests

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#524]
In mining tests, work on restoring good state even after a test fails. Currently the test run exits on test failure.

**Comment by dev1644** [comment]
Does this issue require some work?

**Comment by elenadimitrova** [comment]
It does indeed. You can reproduce the condition described here by breaking a reputation mining test and running `test:contracts` (you can just run one `describe` test set where your broken test is to minimise run time as the whole test suite takes about an hour to run end to end). What you'll notice is that after the broken test fails, no subsequent tests are run as they fail on `"before each" hook`.

**Comment by dev1644** [comment]
I was able to produce this behaviour in only two test files `types-of-disagreement.js` & `dispute-resolution-misbehaviour.js`, the rest of the tests of Reputation-Mining are not exiting upon a single failure.

**Comment by elenadimitrova** [comment]
That sounds right @dev1644 , sorry for confusing you and saying all rep mining tests display this behaviour. These 2 test files introduce disagreements in reputation root hash submissions and what we have in a way of cleanup in `finishReputationMiningCycleAndWithdrawAllMinerStakes` clearly isn't cleaning everything up properly.

**Comment by dev1644** [comment]
Sure, I will take a look and will notify my findings.

**Comment by dev1644** [comment]
Yes, `finishReputationMiningCycleAndWithdrawAllMinerStakes` isn't cleaning everything.
In `finishReputationMiningCycleAndWithdrawAllMinerStakes`, there are some cases in which `nSubmittedHashes` is greater than 1 and `nInvalidatedHashes` is zero, in that case, rest body of `finishReputationMiningCycleAndWithdrawAllMinerStakes` is not executing and thus the state is not restored.
Currently, I am trying to fix it, any other information/suggestion will also help me in speeding up the process.

**Comment by elenadimitrova** [comment]
The release backlog is thinning so I'm starting on this as well. Below are some thoughts.
The reputation mining process life cycle is at a minimum 24h long, the stages it goes through are as follows:
`submitRootHash` - called at least once by mining clients. If more that 1 hash is submitted, dispute resolution steps follow, otherwise if only one hash was submitted, the dispute resolution steps are skipped and the hash can be directly confirmed.
Dispute resolution
Each client must go through these steps individually:
`confirmJustificationRootHash`
`respondToBinarySearchForChallenge`
`confirmBinarySearchResult`
`respondToChallenge` (this call will fail for any bad clients)
`invalidateHash` ( called on all bad clients' submissions)

Once there's only one remaining good hash, we can call  `confirmNewHash` on it which completes the mining cycle and sets it as the current reputationRootHash for the Network.

**Comment by elenadimitrova** [comment]
The simplest solution is probably, when we hit [this](https://github.com/JoinColony/colonyNetwork/blob/develop/helpers/test-helper.js#L664) 
to just reset the network and reputation mining cycle completely instead of trying to "untangle" the dispute state.

**Comment by dev1644** [comment]
Yes, the network needs to be reset if it ever goes into `else` part.

**Comment by elenadimitrova** [comment]
@dev1644 are you going to try and do this or shall I? We are trying to close off the remaining backlog which only has 2 left unassigned items (of which this is one) so completing this is a priority atm.

**Comment by dev1644** [comment]
@elenadimitrova I am going to try it again.

**Comment by dev1644** [comment]
I have created a pull-request #583, I used snapshots to restore the Good old state in case we can't untangle the disputed state.
