### ISSUE TITLE
Add support for 3tx Payments

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#527]
There is a desire for support at the contract level for making payments in as few transactions as possible. Following January's research summit on modularity (see [writeup](https://docs.google.com/document/d/1zWVQ8cuDYaX1dsiSlnII39QV6ykmGH5_66CX6ABfecI/edit)), we would like to support a "3 transaction" payment flow, breaking down as follows:

- Permissions - Only Colony admins are able to create and subsequently amend a payment. Any admin should be able to amend any payment in their colony. There is appetite from product team to limit those powers to the narrower domain admins group when horizontal modularity is implemented.
- Payment will contain payment to a single user in a single token or eth denomination.
- Creating the payment sets recipient, token, amount, source domain (all aforementioned are mandatory props) and optionally skill. 
- Funding the payment (from the source domain).
- Claiming the payment (anyone can claim on behalf of the recipient).
- Reputation is earned only by the recipient (not the payment admin), in the payment domain and optionally in the skill (if this is assigned). The reputation amount will be equal to that earned by completing a task and getting a "meets expectations" rating of `2` i.e. reputation = token (or eth) amount
- Collect reward and network fees on payouts

Further, a "1 transaction" flow can be implemented on top of this through a separate contract (a simple "module" which defines, funds, and claims a payment on behalf of a recipient).

**Comment by kronosapiens** [comment]
What that means is that I can call the `claimPayment` function on your behalf to have money sent to your account. This solves the "first ETH" problem since someone with no ether couldn't even claim their payment, but I can have the "first ETH" payment sent to their account on their behalf. It doesn't mean that I can have someone else's payment sent to _my_ account.

**Comment by elenadimitrova** [comment]
Further questions:
- Domain is mandatory on task, will it be mandated on payments? Same for skills.
- We plan to support multiple skills per task, do we want to allow for multiple skills per payment as well?
- Are we collecting network and reward fees on payouts the same way we charge tasks?
- Will there be any additional rules needed around the funding and claiming of a payment, i.e. can we withdraw a payment back into the parent domain at any point? In tasks we have due dates and completion status to govern that. 
- Can the payment amount, domain, recipient, skill or any other property change after it's created? What permissions if any are needed?
- Can a Payment be cancelled?

**Comment by kronosapiens** [comment]
I'll let others answer as well but my guess would be payments should be as similar as possible to tasks in these regards: domain and skill(s), but with skills optional; same fees; completion status locks funds (but no due date); same permissions as tasks (i.e. can change but once recipient is assigned need multisig to change); same cancellation rules. The "3tx flow" without a multisig involves the manager creating the payment and setting the parameters _before_ assigning the recipient. If they assigned the recipient first, then they might need a multisig to change.

**Comment by elenadimitrova** [comment]
And specifically for earning reputation, to clarify that the "only colony home token earns you reputation" rule should still apply. This is more of a statement than a question.

**Comment by elenadimitrova** [comment]
Another question: Should a payment support single token payment only? i.e. does it make sense from the product side for a payment to have one recipient for 1 token and 1 amount or does it need to be more complex like we have in Tasks, e.g. payout for a task role can be unlimited number of combinations of tokens and ETH.

**Comment by collinvine** [comment]
I'll leave my preliminary answers here. I'd encourage a call if we find there's anything that we need to discuss in more detail.

> Domain is mandatory on task, will it be mandated on payments? Same for skills.

We'd like Domain to be mandatory, and be set at the root domain as a default.
Skills should be optional, not mandatory. 

> We plan to support multiple skills per task, do we want to allow for multiple skills per payment as well?

Yes.

> Are we collecting network and reward fees on payouts the same way we charge tasks?

Yes.

> Will there be any additional rules needed around the funding and claiming of a payment, i.e. can we withdraw a payment back into the parent domain at any point? In tasks we have due dates and completion status to govern that.
> Can the payment amount, domain, recipient, skill or any other property change after it's created? What permissions if any are needed?
> Can a Payment be cancelled?

I agree with @kronosapiens answer: _Same permissions as tasks (i.e. can change but once recipient is assigned need multisig to change)_

One thing I'd like to understand more here is the assignment experience. As I understand it, the 3txs are:

* Create
* Fund
* Claim (anyone can call this)

How does assignment factor into that? I'd like to better understand this, else I feel I'm not able to properly think about this. 

Could you @elenadimitrova or @kronosapiens help me here?

> "only colony home token earns you reputation" rule should still apply. This is more of a statement than a question.

Agreed.

> Should a payment support single token payment only?

No.

**Comment by kronosapiens** [comment]
With regards to the 1tx "Create" flow, my suggestion is that we implement both a flexible set of Payment functions (essentially the same as the Task functions), and then wrap them in a `makeQuickPayment` function which looks like this:

```
function makeQuickPayment(address recipient, uint256 domain, address token, uint256 amount) public auth {
  makePayment(domain);
  setFunding(paymentId, token, amount);
  assignWorker(paymentId, recipient);
  finalizePayment(paymendId);
}
```

So the first transaction is a call to `makeQuickPayment`, but in other settings people can use the underlying functions to assign multiple token payouts, multiple skills, etc. when they want more fine-grained control.
