### ISSUE TITLE
Reputation Decay calculation

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#54]
### 7.6.4 The Reputation Decay Calculation
The reputation decay process was described above as being continuous. In practise, it will decay by a small, discrete amount during each reputation update cycle following an exponential decay.
However, such a calculation is not possible to do accurately on-chain during the resolution protocol, so we must use an approximation. The details of the approximation we use, and a proof that this approximation is accurate and will not affect the running of (active) colonies can be found in Appendix B.

**Comment by FredrikBixo** [comment]
I will start looking into this issue

**Comment by area** [comment]
To begin with, just concentrate on the implementation of this decay calculation and the accuracy of the implementation that you come up with when repeatedly iterated; if you want to put it on one of our contracts for testing purposes, it should go on the `ReputationMiningCycle` contract. Once #189 is merged, we can start looking at implementation and acknowledgement of reputation decay from the perspective of the mining client.

**Comment by elenadimitrova** [comment]
@FredrikBixo you probably haven't started working on this, considering our last Gitter conversation so wanted to let you know that @area is working on this now
