### ISSUE TITLE
Visualise current reputation state

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#550]
Working with a Patricia tree structure generally requires vivid imagination which shouldn't be relied on. A [visual aid similar to this](https://beta.observablehq.com/@cdetrio/merkle-patricia-trie-viz) will help better understand current reputation state. The two trees to model are reputation state tree (`this.reputationTree`) and justification tree (`this.justificationTree`) in the client.

**Comment by kronosapiens** [comment]
D3 might be good for this: https://bl.ocks.org/adamfeuer/b7d545f3fa025d6ed56183129a7ee01c

**Comment by kronosapiens** [comment]
Also noting that visualizing these are desirable:

1. The reputation log entries.
2. The state of reputation mining disputes
