### ISSUE TITLE
Reputation Mining Visualizer

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#566]
We would like to develop a visualizer which can help us understand the state of the current reputation mining cycle. Three things we would like to see:

1. The reputation log entries.
2. The state of reputation mining disputes
3. The current reputation tree itself.

Items 1 & 2 can be drawn from `ReputationMiningCycle.sol`, while item 3 requires data from a mining client.

**Comment by elenadimitrova** [comment]
Is this different in scope to #550 ?

**Comment by kronosapiens** [comment]
Oh, I forgot about that one. Nope, I'll roll them up together.
