### ISSUE TITLE
Emergency Shutdown

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#57]
### 7.9 Emergency Shutdown
Section 2.2 described a transaction from a whitelisted address can put a colony into ‘recovery mode’ during which the state can be edited, the effects of bugs can be corrected and upgrades can be made.
Similarly, the reputation mining process will also have an emergency stop-and-repair mechanism (to begin with). This will allow the whitelisted addresses to revert the reputation root hash to a previous version and halt all updates to the reputation state until the issues have been resolved (which will likely involve a contract upgrade). The colonies will be able to continue operations as usual using the reputations of the last valid state, which will be temporarily frozen and not decay.

**Comment by kronosapiens** [comment]
@elenadimitrova is this separate functionality from whats in the pipeline in #270 ?

I suppose the reputation mining stop-and-repair is different, but the function to put the contract into recovery mode is under review.

**Comment by elenadimitrova** [comment]
Yes it is although logic can be reused. #270 deals with recovery mode for colonies only while the reputation mining functionality is managed at the colony network level, e.g. `reputationRootHash` is stored in `ColonyNetworkStorage`
@area anything else to add?

**Comment by area** [comment]
Not really. Some consideration needs to be given to what happens when a cycle is stopped mid-process, but I think most things can be solved by just deploying another `ReputationUpdateCycle`, and pointing colonyNetwork to the new one(s). Log entries can be manually moved over, if necessary, with custom functions on that 'transitional' `ReputationUpdateCycle`.

**Comment by filiplazovic** [comment]
@area Should i be worried about log entries being corrupted/wrong?

**Comment by elenadimitrova** [comment]
Just recording a discussion on this logic I had with @area 
Ultimately, the Meta colony will have the Recovery capability. This type of decisions there would normally go through a vote, but in most cases we'd want to enter recovery as soon as possible in which case the voting process will likely prove too slow. Instead we want an `Authority` for people to be able to put it in to that state, and potentially only the owner (ultimately the Meta Colony) to be able to take it out of that state.

**Comment by elenadimitrova** [comment]
Just as a comparison to the recovery mode capability for a `Colony` https://github.com/JoinColony/colonyNetwork/pull/270
