### ISSUE TITLE
Process for deprecating and ultimately removing global tags

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#573]
Taken from #565 - this seems unrelated to moving to a tag cloud vs a skill hierarchy.

> We will need to decide how skills are to be added / deprecated / removed. Let's assume we have "administration" or "architecture" or "root" functions which perform this and worry about how to trustless-ify those functions in the future (i.e. via the dispute mechanism, a curated registry, or some other mechanism).

Manifestly doable for global skills, but presumably we're comfortable with local skills (i.e. domain skills) not being able to be touched by this process? If I mark a domain as deprecated, what happens to the subdomains? Presumably nothing, otherwise it's gas limited. So then I could still be earning reputation in the deprecated domain through subdomains?

Should we allow skills to be taken out of a deprecated state and used again?

**Comment by area** [comment]
For global skills, I think all we can reasonably do is mark a skill as not being able to be added to a skill or a task, and let the reputation decay away. I don't think we should be able to remove it entirely / reuse the ID, because if I look at a historical task, I should see the correct reputation that was awarded completing it, even if the reputation given by it has long decayed away.

**Comment by kronosapiens** [comment]
That seems reasonable. I don't see any compelling reason why we _shouldn't_ allow a deprecated tag to be revived (vs. creating a new one with the same name) if that is wanted.
