### ISSUE TITLE
Decide on 'undeprecating' global skills

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#590]
Once #573 is merged, there will be a mechanism for preventing users assigning deprecated global skills to tasks and payments. It is an open question whether this deprecation process should be able to be reversed, allowing a previously deprecated skill to be assigned once more to tasks.

**Comment by kronosapiens** [comment]
It seems like it's more of a product question than a technical question, since "undeprecating" a skill amounts to little more than flipping a boolean.

**Comment by area** [comment]
We're removing global skills entirely (#1130) so this is no longer a concern.
