### ISSUE TITLE
Colony creation bundle

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#607]
In order to minimise the number of transactions which are part of the "Colony creation" flow in the dApp, associated with setting up a new Token, Colony, extension contracts and associated wiring (see list below) we should investigate how much of these contract calls we can bundle in a single call as part of an external contract. It is likely that the entire set of transaction will exceed the block gas limit, so find a way around that too. 

- Create token
- Create colony
- Register colony ENS name
- Create `TokenAuthority`
- Set token authority on the token
- Deploy `OneTxPayment` for colony
- Give that permissions
- Deploy `OldRoles` for colony
- Give that permissions

**Comment by kronosapiens** [comment]
Picking this up.

Initial thoughts:
 
- Combine colony creation (`createColony(address _tokenAddress)`) with registering the colony ENS label (`registerColonyLabel(string memory colonyName, string memory orbitdb)`). Either make `createColony` always call out to `registerColonyLabel`, or bundle them into a second function called `createColonyWithLabel`.

- Jointly or severally with above, combine deploying the Token Authority with colony creation. It's a small contract (less than 1kb), and of the three arguments (`constructor(address _token, address _colony, address[] memory allowedToTransfer)`), two of them are already available in colony creation.

- Creating a one-touch extension deployment flow which deploys the extension AND assigns the correct permissions. One way this could be achieved would be by creating a single, upgradable, `ExtensionFactory` contract which can deploy all "approved" or "official" extensions. This factory would know, for every extension, know the permissions needed, and be able to deploy the extension and assign permissions in one transaction. This factory would need to be assigned root permissions in the colony, which can be done during colony creation, or as a separate transaction.

**Comment by collinvine** [comment]
That would be a good improvement, it's been a pain point for users so far.

Is there any way to reduce that even further? Could we get it down to 3 tx?

**Comment by kronosapiens** [comment]
If we wanted to drop the "BYOT" functionality, we may be able to include Token creation and configuration as part of the "create colony" transaction, which would drop two more transactions.

**Comment by collinvine** [comment]
No we need to keep that as an option.

We couldn't combine Create token, Create colony, and Register colony ENS name into one?

And then combine the other 6 into another bundle?

**Comment by kronosapiens** [comment]
That was my meaning -- not drop forever, but just drop for this particular UX by combining create token with create colony (if you create the token when you create the colony, then you can't BYOT).

**Comment by collinvine** [comment]
I see. And for the other flow, we keep it.

I'm intrigued!
