### ISSUE TITLE
ColonyNetworkENS returns wrong domain

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyNetwork#645]
## Summary

The `ColonyNetworkENS` `lookupRegisteredENSDomain` function assumes that the domain `joincolony.eth` is being used as the root node. This will not be true for testnet deployments such as on Goerli, where ENS uses the `.test` TLD.

## Steps to Reproduce

Calling `lookupRegisteredENSDomain` on Goerli for an address which has been registered will return a domain ending in `.eth`.

```js
// truffle console example
IColonyNetwork.at('0x79073fc2117dD054FCEdaCad1E7018C9CbE3ec0B').then(cn => cn.lookupRegisteredENSDomain('0x45771b2801Ec5A9dFe8C348Da31f9a62813E105B'))
```

## Possible Solution

We could use a reverse resolver to determine the ENS domain being used with the `ColonyNetworkENS` contract, or we can manually keep track of this value in that contract.

Alternatively just remove the part which the contract doesn't know about, and include some client-side handling of this in colonyJS (if we know which network we're connected to, we can lookup against some hardcoded values for which root ENS domain the contract uses). In that case, the contract function would return e.g. `myusername.user`/`mycolony.colony`, and on the client side have `.joincolony.test`/`.joincolony.eth` appended.

**Comment by area** [comment]
Closed by #872
