### ISSUE TITLE
Improve DevOps monitoring

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#662]
Historically, for closed betas on private chains, we had monitoring provided by Google that alerted us to downtime. We should have something equivalent for the reputation mining cycle contracts at the very least.

**Comment by elenadimitrova** [comment]
Also consider watching key contracts (EtherRouter for ColonyNetwork, MetaColony, CLNY, TokenLocking, ReputationMiningCycle) for:
- DoS attacks. This is probably watching for a lot of (failed?) transactions (coming from the same address?)
- Authority and owner changed events, i.e. `LogSetAuthority` and `LogSetOwner` from `DSAuth`

Until we get a proper admin interface it'll also be nice to get notified on a new Colony creation, although I admit this isn't devops business but more network admin area of interest.

**Comment by area** [comment]
So far, I've set up Stackdriver monitoring for the errors coming from the miner and the self-hosted parity node that we have.

**Comment by area** [comment]
Closed in #629
