### ISSUE TITLE
Investigate eth-gas-reporter changes

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#669]
See issue https://github.com/cgewecke/eth-gas-reporter/issues/106

1. A recent update to `eth-gas-reporter` means that contracts using the delegateProxy pattern (i.e. ~all of our contracts) are no longer reported, which is no bueno. Investigate and repair.

2. Supposedly there is a new tool which shows the diff of gas consumption for PRs, which would be helpful. Investigate and add.

**Comment by cgewecke** [comment]
Hi @kronosapiens :)  
> the delegateProxy pattern (i.e. ~all of our contracts) are no longer reported 

They're still reported - the newer version adds support for EtherRouter (as an option) and for delegate proxies generally. The note left [106](https://github.com/cgewecke/eth-gas-reporter/issues/106#issuecomment-507941358) just recommends you don't bother changing anything because this option doesn't improve data collection in your case and runs more slowly. 

There *is* a greenkeeper build-break ticket here (#668) but it looks like it might be the coverage job [randomly failing w/ a timeout](https://circleci.com/gh/JoinColony/colonyNetwork/9071?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link).

**Comment by kronosapiens** [comment]
As @cgewecke has noted, things seem to be back in order as of the most recent build (https://circleci.com/gh/JoinColony/colonyNetwork/9155). Looking over the changes mentioned to make sure everything is in order and then will look into the gas change monitor.

**Comment by kronosapiens** [comment]
@cgewecke you mentioned that the "wild guess" strategy seems to work well -- are you referring to `resolveByMethodSignature` here? https://github.com/cgewecke/eth-gas-reporter/blob/e5ff36e8c109a059cc92fedfaf83e35014b003ef/lib/proxyResolver.js#L25

**Comment by cgewecke** [comment]
@kronosapiens Yes, exactly. That seems to produce the same data but it's faster (makes many fewer additional calls)

**Comment by kronosapiens** [comment]
@cgewecke makes sense. Although this sounds like one of those situations where the code works "by accident" and as a result might stop working at some point in the future because of an unrelated change, and there's no expectation that the functionality would continue to work as-is. Not a problem, just something we should note so we can don't have to go over this again if/when the time comes.

**Comment by cgewecke** [comment]
Oh also @kronosapiens if you're trying the CI check thing out, I believe this `codechecks.yml` config should make everything work normally out of the box :
```yml
checks:
  - name: eth-gas-reporter/codechecks
settings:
  branches:
    - develop
    - master
```

You also have to add a dev dependency here
```
npm install --save-dev @codechecks/client
```

And lastly it's a github service so you have toggle it on at [codechecks.io](https://codechecks.io/) and copy-paste their token into your CI environment variable settings. Please just lmk if you run into any difficulties there.

**Comment by kronosapiens** [comment]
Ok, I've run the gas tests locally with and without the explicit `proxyResolver: "EtherRouter"` setting, and the results are virtually identical:

Without: 5m33.161s
With: 5m32.159s

They produce virtually identical data (one function had a slightly higher `max` value).

Looking at the timing in Circle, however, the explicit `proxyResolver` flag seems to shave off quite a bit of time (compared to the most recent merged PR):

[Without](https://circleci.com/gh/JoinColony/colonyNetwork/9155): 388.31s 
[With](https://circleci.com/gh/JoinColony/colonyNetwork/9186): 268.14s

Which is a big difference but also directionally opposite to what @cgewecke observed. Note also that the data are completely identical now.

However if we look at the builds themselves, the "Without" build ran overall in 2:27:50 (8870 seconds) while the "With" build ran in 1:39:20 (5960 seconds), for no particular reason that I can discern (the code and tests should be identical in both builds) -- looking at the times, every section of build ran relatively longer in the "Without" case. So if we normalize the gas test times using the overall build times (x1.49), that would give us a modified "With" time of `268.14 * 1.49 = 400`, which _is_ slightly slower than without (by about 12 seconds).

So while these data are a bit confusing and contradictory, I'm going to suggest we follow @cgewecke's suggestion and leave things as-is for now.

**Comment by kronosapiens** [comment]
@cgewecke tried setting up codechecks as per your advice (see [here](https://github.com/JoinColony/colonyNetwork/pull/676/files)), but getting this error in Circle:

```
#!/bin/bash -eo pipefail
npx codechecks
CodeChecks Client v.0.1.5
https://codechecks.io

Executing 1 codechecks files
Base branch: 85356dff

Executing codechecks.yml...

Error occured:  Module eth-gas-reporter/codechecks couldn't be found. Tried: 
- @codechecks/eth-gas-reporter/codechecks
- eth-gas-reporter/codechecks

Exited with code 1
```

Any guesses as to what I did wrong? I'm wondering if maybe I need to run `yarn` here?

```
      - run:
          name: "Running gas cost diff check"
          command: npx codechecks
```

**Comment by kronosapiens** [comment]
Heyyyyyyy

https://github.com/JoinColony/colonyNetwork/pull/676/checks?check_run_id=170075704

**Comment by cgewecke** [comment]
@kronosapiens Oh good. The report's kind of wide, I wonder if we can do something about that....

**Comment by kronosapiens** [comment]
Ok, I'm dumb -- my earlier local timing tests were run before bumping the `eth-gas-reporter` version. Re-running locally the differences are obvious:

Without `proxyResolver: "EtherRouter"`: 5m45s
With `proxyResolver: "EtherRouter"`: 6m09s

So the explicit flag adds an overhead of 7%.
