### ISSUE TITLE
Investigate test timeout flickers

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#711]
Very often we get Greenkeeper issues raised due to tests timing out -- GK believes that the test failures are due to package updates, which they are not, as often re-running the build will solve the issue. These GK false positives take up time and we should get to the root issue.

**Comment by area** [comment]
#706, #705, #701 was spotty, if not a timeout, so probably counts. #695. And possibly more.

**Comment by kronosapiens** [comment]
Noting that this problem seems to be getting more common -- just today two of my builds failed because of timeouts.

**Comment by area** [comment]
These seem to have disappeared so... closing.
