### ISSUE TITLE
PFPs and the Funding Queue

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#74]
### 8.2.12 PFPs and the Funding Queue
Active Priority Funding Proposals take priority over Basic Funding Proposals and so they are placed at the top of the funding queue. They are ordered by the total reputation of the domain that voted to activate it and, in case there is a tie, by the actual amount of reputation that voted to activate.
Thus PFPs that are higher in the domain hierarchy come before those lower down.
As with BFPs, any user can ‘ping’ an active PFP at the top of the queue to cause the contract to update the funds available to the recipient pot. `TotalPaid`, `LastUpdated` and `CurrentState` are updated as required.

**Comment by kronosapiens** [comment]
Rolling into #73
