### ISSUE TITLE
The 24h waiting period for PFP updates

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#75]
### 8.2.13 The 24h waiting period for PFP updates
Priority Funding Proposals take precedence over Regular Funding Proposals. To avoid the situation
in which long running PFPs block the BFP process entirely, a limit is placed on how often and
PFP can be updated (‘pinged’). We say a PFP can only be pinged when it is first activated* and
when its `LastUpdated` time is at least 24 hours old.
The result of this rule is that fast payments are still possible — in such a case the PFP’s rate is set very high and the proposal is fully funded at the initial ping, while also allowing long-term lower-rate PFPs that do not block the entire BFP process.

* In this initial update the time elapsed since last update is taken to be 24 hours.

**Comment by kronosapiens** [comment]
Rolling into #73
