### ISSUE TITLE
When is a Funding Proposal eligible to receive funding?

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#76]
### 8.2.14 When is a Funding Proposal eligible to receive funding?
A Regular Funding Proposal may receive funds when pinged if it is active and at the top of the BFP funding queue and when the `LastUpdated` time of the PFPs are less than 24 hours old. A Priority Funding Proposal may receive funds when pinged if it is active and all PFP ahead of it in the funding queue have been updated less than 24 hours ago.*
* In order to avoid hitting the gas limit due to unbounded loops, it will be necessary to maintain two orderings for the PFPs, one by priority and one by LastUpdated.

**Comment by kronosapiens** [comment]
Rolling into #73
