### ISSUE TITLE
Subdomain Takeover

### ISSUE THREAD

**Issue by TrustDompet** [JoinColony/colonyNetwork#768]
Subdomain Takeover
=========

Vuln: http://help-backend.colony.io/

simply go to https://www.intercom.com/customer-support-software create a new account buy the service or get a free demo for 14 days

Then visit https://app.intercom.io/a/apps/yourid/articles/site/settings and add the subdomain that's giving error in custom domain field

Any one can takeover your subdomain :)

**Comment by TrustDompet** [comment]
This is extremely vulnerable to attacks as a malicious user could create any web page with any content and host it on the colony.io domain. This would allow them to post malicious content which would be mistaken for a valid site. They could steal cookies, bypass domain security, steal sensitive user data, etc.

**Comment by area** [comment]
Just in case you weren't the same person who emailed us about this:

Thanks for letting us know about this. I do not believe it was a vulnerability though - the help-backend.colony.io subdomain is still registered to us on the Intercom side, it is just disabled, and so it is my understanding that it is not possible for someone else to register it with intercom and take over the domain. I confirmed this would be the case with intercom themselves originally, as well as by trying it myself. Indeed, I just tried myself again with a test account earlier this week, and got the message: "There was a problem saving your settings: 'help-backend.colony.io' has already been taken."

You are correct it is not best practises however, so the CNAME has been removed for now until it is re-enabled.

**Comment by TrustDompet** [comment]
You removed the cname I give you alert then you remove the DNS then it is
my right to ask you a bounty

Send my bounty and tell me what options do you have for payment

**Comment by area** [comment]
The [bounty program](https://colony.io/dev/docs/colonynetwork/bug-bounty-program-overview) I assume you are referring to clearly states that it applicable only to the solidity contracts within this repository, which this clearly wasn't. In addition, as I said in my previous reply, the takeover you described was not possible, so even if it was in scope I'm not convinced that a payout would have been warranted.

**Comment by TrustDompet** [comment]
As you wish I do my hard work for you and your are not paying for my work
