### ISSUE TITLE
Editing Funding Proposals

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#77]
### 8.2.15 Editing Funding Proposals
The creator of a funding proposal may edit the `TotalRequested` property of a funding proposal at any time, but doing so resets the reputational support that the proposal has in the funding queue to zero. The intention here is for changes to funding to be potentially quick to achieve with the agreement of others in the colony if the requirements for the recipient pot change (e.g. the scope of a domain increases).

**Comment by kronosapiens** [comment]
Closing this -- this functionality can be equivalently achieved by cancelling & creating a new funding proposal.
