### ISSUE TITLE
Update OneTxPayment to handle multiple tokens

### ISSUE THREAD

**Issue by kronosapiens** [JoinColony/colonyNetwork#780]
Currently, our `OneTxPayment` extension supports only a single token/amount -- the initial thinking was since it takes one transaction to add a token, `OneTx` would imply one token. After some thought, it seems as though it wouldn't be the worst thing in the world to extend the interface to take a **list** of tokens/amounts and apply them all. The normal risk of unbounded arrays don't really apply here, since it's a one-transaction deal anyway, so there's no risk of collateral damage if the tx fails.

**Comment by area** [comment]
Superceded by #806
