### ISSUE TITLE
Paying out a Task Bounty

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#79]
### 8.3 Paying out a Task Bounty
Ultimately, via the mechanism described above, some tokens have found their way into a pot associated with a task. Upon completion of the specified work and approval by the evaluator, the worker has earned the contents of the pot. However, even once the work has been approved, there remains a period of time before the funds can be requested to be paid out by the receiving address. 
This is enforced to allow a period where a user of the colony can object to the payout, accusing it of fraudulence or similar. If a user objects to the payout, they can raise an objection to void the task payout. The objection may be raised to a parent domain of the task in question — or even escalated to the colony domain itself. The choice of domain lies with the user making the objection. Users vote to resolve any resulting disputes with votes weighted by their reputation in the domain the objection was raised to. In the event that their dispute is upheld, the funds can be returned to the domain that contained the task. If the voters approve of the payout, no changes are made and the user will be able to claim their payout after all.
While a payout is under dispute, the timeout period continues to run. After the end of the dispute period, no more objections are able to be raised, but any existing objections are resolved before payout is allowed. This is to prevent users being able to continually raise disputes to prevent payout.
Once the tokens have been paid out, they are under the control of the user — there is no way to reclaim the funds. The funds have to cross the ‘Cryptographic Rubicon’ somewhere in the system (by the nature of the blockchain), and it makes sense to do so here.

**Comment by kronosapiens** [comment]
Closed in favor of #733
