### ISSUE TITLE
Be able to simultaenously add and remove roles

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#878]
It would make product's life much easier if `setUserRoles` were able to set and unset roles at the same time.

**Comment by area** [comment]
I think this probably also pushes us towards a separate 'Justification' event with the prose in for #877 rather than adding it to each individual event that is relevant.

**Comment by kronosapiens** [comment]
Mm, the only issue is that if we use events to render a UI for permissions, then dropping the per-role event requires a different approach... is two function calls (one to add, one to remove) so bad?

**Comment by area** [comment]
> A justification-string approach doesn't seem like it would lend itself well to rendering a UI.

I don't follow this? It's a justification for all of the permission changes being done.
