### ISSUE TITLE
Enabling extensions in specific domains after they are installed in root

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#890]
While root permissions are required to install an extension, in theory, permissions could only be awarded to an extension in a subdomain. We must make sure our extensions work in that scenario, and while I believe they should, as far as I can see we don't have tests along those lines.

**Comment by kronosapiens** [comment]
We discussed this in regards to funding proposals -- a funding proposal without the right permission could block up the whole queue. Our preferred solution is to make a permissions check on every funding proposal before pinging, and setting reputation to 0 if the permission check fails.
