### ISSUE TITLE
Hybrid voting

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#91]
### 9.3.3 Hybrid voting
A hybrid vote would allow both reputation holders and token holders to vote on a decision. We envision such a vote being used when the action being voted on would potentially have a sizeable impact on both reputation holders and token holders. This would include altering the supply of the colony tokens beyond the parameters already agreed (see Section 5.1) or when deciding whether to execute an arbitrary transaction (see Section 11.4).
In order for a proposal to successfully pass through a hybrid vote, both the reputation holders and the token holders must have reached quorum, and a majority of both reputation and token holders who vote must agree that the change should be enacted.

**Comment by kronosapiens** [comment]
Rolling into #90
