### ISSUE TITLE
Revenue and Rewards

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#92]
**_What is Colony Revenue?_**
A colony may sell goods and services in exchange for tokens, for Ether or for one of the ERC20 tokens whitelisted for use on the network. Whenever a colony receives such payments, we say that the colony has earned revenue.*
Revenue is distinct from a colony’s working capital. The latter is the sum of all tokens held by the colony for use in funding requests i.e. the funds in the pot belonging to the colony-wide domain in the colony (see Section 8), while the former, revenue, has its own dedicated pot.
*A colony contract can of course receive any tokens, even those that are not whitelisted. Only payments that can be used within a colony for funding proposals and tasks payouts count as revenue.
**_What are Colony Rewards?_**
There is some expectation that some fraction of any Ether or other valuable tokens earned by the colony are paid out to their token holding members. ’Members’, in this context, means accounts holding both tokens and reputation in the colony. Whenever a colony distributes a portion of earned revenue to its token holding members, we say that the colony is paying out rewards. 
It is expected that most of the revenue will not go towards rewards, but towards replenishing the working capital.

**Comment by kronosapiens** [comment]
Closing -- this functionality is implemented.
