### ISSUE TITLE
Add emitReputationReward as a function

### ISSUE THREAD

**Issue by area** [JoinColony/colonyNetwork#920]
~~This function should be able to emit a reputation reward as well as a penalty.~~

A new, root level function should be added to the Colony contracts that allows reputation to be awarded to an address.

**Comment by kronosapiens** [comment]
I am concerned about this functionality -- by allowing any arbitrator to mint reputation, a low-level subdomain arbitrator could grant themselves millions of reputation in that subdomain, and thus in the root domain, allowing them to take over the colony.

**Comment by kronosapiens** [comment]
After a call with @jakzilla and @area , we will make this a root-level function, which addresses my concerns.
