### ISSUE TITLE
The token auction

### ISSUE THREAD

**Issue by elenadimitrova** [JoinColony/colonyNetwork#97]
### 10.3.2 The token auction
The colony tokens collected are auctioned off by the Colony Network Contract, with the auctions denominated in Common Colony Tokens, the proceeds of which are given to the Common Colony as revenue. These auctions — one for each type of token collected — occur on a regular basis of once a month.
We believe such behaviour would be beneficial for the Common Colony Token holders (whose Common Colony Tokens gain value by having an explicit use beyond reputation mining) and the Common Colony itself (which turns the fees into Common Colony Tokens which it can then use to fund further development of the network without explicitly buying them back or creating more, diluting existing holders). It also provides an immediate mechanism of price discovery for the colony tokens, which are unlikely to be traded on third-party exchanges until much later in the lifetime of the colony. By auctioning off the collected tokens, we also prevent the Common Colony collecting a large number of different tokens that it has to manage, which would prove cumbersome and annoying for the colony.

**Comment by elenadimitrova** [comment]
Suggestion for the auction model:

- Start a blind auction for a given token and quantity
- One bid per account and max of 20 bids are allowed 
- Bid secret submission and reveal periods are each 1 week long
- Bid secrets are submitted containing a bid price and quantity desired
- Secret bids are revealed during which we order bids by descending price
- We finalise the auction by iterating over the bids starting from the highest and assign quantity desired until supply depletes 
Potentially we can also:
- Lock the CLNY they bid (most likely we'll have to do this)
- Allow overwriting and bid retraction
- Equalise Token price for winning bids so everyone ends up paying the same price

Comments welcome @area

**Comment by area** [comment]
> One bid per account and max of 20 bids are allowed
So I wait for the auction to open, submit 0.00000000000001CLNY from each of my 20 addresses, and win everything for approximately nothing apart from the gas to make sure I got in first?

>iterating 
I've got conniptions already. Is this why you want to limit to 20 bids?

>Lock the CLNY they bid (most likely we'll have to do this)
I think this is necessary.

> Equalise Token price for winning bids so everyone ends up paying the same price
I think I like this if it's not too gassy.

**Comment by elenadimitrova** [comment]
That is exactly why they are limited, yes. But I see the problem with that.

Updated with some change suggestions. The one thing I couldn't work out is how to order bids by price, so I simply split the bidders by average price offered, allowed those above to claim first, then if anything left the rest can claim on a first-come-first-served basis. Do you see a fairer way of distributing this?

**Comment by elenadimitrova** [comment]
After some offline conversations with @area we came to the conclusion a [Vickrey style auction](https://en.wikipedia.org/wiki/Vickrey_auction) will work best for this. The motivation is driven by the following main points:
- Ordering revealed bids with a linked list in constant gas is possible if the bidder tells us where in the order their revealed bid should be placed. Unlike the token-weighted voting however, where each linked list is address specific, here reveal transactions are likely to fail as they'll be order dependent on each other. 
- Considering the amount of tokens to be sold in each auction is relatively small, e.g. if a colony closes 100 tasks per month, and we get 1% off that, the earnings will be ~ 1 average task worth of tokens, we can sell all tokens in one go and apply a simpler auction model, e.g English or Vickrey to the entire amount of tokens. That is, the highest bidder wins all auctioned tokens.
